apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-spring-boot-demo
  labels:
    app: kotlin-spring-boot-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kotlin-spring-boot-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0      # Zero downtime
      maxSurge: 1            # Allow one extra pod during update
  template:
    metadata:
      labels:
        app: kotlin-spring-boot-demo
    spec:
      containers:
        - name: kotlin-spring-boot-demo
          image: fmahmud26/kotlin-spring-boot-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
      imagePullSecrets:
        - name: dockerhub-secret
