apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-spring-boot-demo
  labels:
    app: kotlin-spring-boot-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kotlin-spring-boot-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kotlin-spring-boot-demo
    spec:
      containers:
        - name: kotlin-spring-boot-demo
          image: fmahmud26/kotlin-spring-boot-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
          resources:                     # <-- Put it here
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
      imagePullSecrets:
        - name: dockerhub-secret
