apiVersion: v1
kind: Service
metadata:
  name: kotlin-spring-boot-demo
spec:
  type: LoadBalancer
  selector:
    app: kotlin-spring-boot-demo
  ports:
    - protocol: TCP
      port: 80         # ELB listens on 80
      targetPort: 8080 # Container listens on 8080
